- import_role: role=common/kinit
  become_user: "{{ hdfs_user }}"

- import_role: role=common/kinit
  become_user: "{{ yarn_user }}"

- import_role: role=common/kinit
  become_user: "{{ mapred_user }}"

- name: create "hdfs.nohup.out" file with correct owner
  become: yes
  copy:
    content: ""
    dest: "{{ opt_dir }}/hadoop/logs/hdfs.nohup.out"
    owner: "{{ hdfs_user }}"
    group: "{{ hadoop_user }}"

- name: start hdfs
  when: not hdfs_is_running
  become: yes
  shell: "nohup {{ opt_dir }}/hadoop/sbin/start-dfs.sh 2>&1 > {{ opt_dir }}/hadoop/logs/hdfs.nohup.out"

- name: start yarn
  when: not yarn_is_running
  become_user: "{{ yarn_user }}"
  shell: "nohup {{ opt_dir }}/hadoop/sbin/start-yarn.sh 2>&1 > {{ opt_dir }}/hadoop/logs/yarn.nohup.out"

- name: start mapreduce history server
  when: not mapred_is_running
  become_user: "{{ mapred_user }}"
  shell: "nohup {{ opt_dir }}/hadoop/bin/mapred --daemon start historyserver 2>&1 > {{ opt_dir }}/hadoop/logs/mapred-history-server.nohup.out"
