- import_role:
    role: common/register_running_services

- name: create "hdfs.nohup.out" file with correct owner
  become: yes
  copy:
    content: ""
    dest: /opt/hadoop/logs/hdfs.nohup.out
    owner: hdfs
    group: hadoop

- name: start hdfs
  when: not hdfs_is_running
  become_user: "{{ 'root' if use_secure_mode else 'hdfs' }}"
  shell: |
    . /etc/bash.bashrc
    nohup /opt/hadoop/sbin/start-dfs.sh > /opt/hadoop/logs/hdfs.nohup.out

- name: set Erasure Coding policy
  when: need_format and use_erasure_coding
  become_user: hdfs
  shell: |
    . /etc/bash.bashrc
    kinit hdfs/$(hostname -f) -kt /etc/security/krb5.keytab
    hdfs ec -setPolicy -path / -policy {{ erasure_coding_policy }}

- name: start yarn
  when: not yarn_is_running
  become_user: yarn
  shell: |
    . /etc/bash.bashrc
    nohup /opt/hadoop/sbin/start-yarn.sh > /opt/hadoop/logs/yarn.nohup.out

- name: start mapreduce history server
  when: not mapred_is_running
  become_user: mapred
  shell: |
    . /etc/bash.bashrc
    nohup /opt/hadoop/bin/mapred --daemon start historyserver > /opt/hadoop/logs/mapred-history-server.nohup.out
