- import_role:
    role: common/register_running_services

- name: start hdfs
  when: not hdfs_is_running
  # become_user: hdfs
  become: yes
  shell: |
    . /etc/bash.bashrc
    nohup /opt/hadoop/sbin/start-dfs.sh > /opt/hadoop/logs/hdfs.nohup.out

- name: start yarn
  when: not yarn_is_running
  become_user: yarn
  shell: |
    . /etc/bash.bashrc
    nohup /opt/hadoop/sbin/start-yarn.sh > /opt/hadoop/logs/yarn.nohup.out

- name: start mapreduce history server
  when: not mapred_is_running
  become_user: mapred
  shell: |
    . /etc/bash.bashrc
    nohup /opt/hadoop/bin/mapred --daemon start historyserver > /opt/hadoop/logs/mapred-history-server.nohup.out
