need_format: False
master_host: "{{ groups['masters'][0] }}"
is_master_host: "{{ inventory_hostname == master_host }}"

need_proxy: False
http_proxy: "http://10.106.79.55:3128"

keytab_path: /etc/security/krb5.keytab
hive_db_name: hive_metastore
