- import_role:
    role: common/register_running_services
  failed_when: hiveserver2_is_running

- name: create user 'hive' in pg
  become_user: postgres
  expect:
    command: createuser -d -P hive
    responses:
      "Enter password for new role": "{{ hive_db_password }}"
      "Enter it again": "{{ hive_db_password }}"
  register: result
  failed_when: result.rc != 0 and ('already exists' not in result.stdout)

- name: create database 'hive' in pg
  become_user: hive
  shell: "createdb {{ hive_db_name }}"
  register: result
  failed_when: result.rc != 0 and ('already exists' not in result.stderr)

- name: init pg schema
  become_user: hive
  shell:
    chdir: /opt/hive
    cmd: |
      . /etc/bash.bashrc
      /opt/hive/bin/schematool -initSchema -dbType postgres

- name: execute shell commands
  become_user: hive
  shell: |
    . /etc/bash.bashrc
    kinit hive/{{ inventory_hostname }} -kt {{ keytab_path }}
    {{ item }}
  loop:
    - /opt/hadoop/bin/hdfs dfs -mkdir -p /hive/warehouse
    - /opt/hadoop/bin/hdfs dfs -mkdir -p /tmp
    - /opt/hadoop/bin/hdfs dfs -chmod g+w /hive/warehouse
    - /opt/hadoop/bin/hdfs dfs -chmod g+w /tmp
