- become_user: spark
  import_role:
    role: common/kinit

- name: create spark logs directory in hdfs
  become_user: spark
  shell: |
    . /etc/bash.bashrc
    /opt/hadoop/bin/hdfs dfs -mkdir -p /spark/logs
