- import_role: role=common/kinit
  become_user: "{{ spark_user }}"

- name: create spark logs directory in hdfs
  become_user: "{{ spark_user }}"
  shell: "{{ opt_dir }}/hadoop/bin/hdfs dfs -mkdir -p /spark/logs"
