- hosts: all
  become: yes
  roles:
    - role: common/register_running_services

- hosts: masters
  become: yes
  roles:
    - role: hive/clean/downloads
    - role: spark/clean/downloads

- hosts: all
  become: yes
  roles:
    - role: hbase/clean/downloads
    - role: hadoop/clean/downloads
    - role: zookeeper/clean/downloads
