- hosts: all
  become: yes
  roles:
    - role: kerberos/configure
      when: (services is not defined or "kerberos" in services) and use_secure_mode
    - role: zookeeper/configure
      when: (services is not defined or "zookeeper" in services) and host_in_zk_hosts
    - role: hadoop/configure
      when: (services is not defined or "hadoop" in services)
    - role: hbase/configure
      when: (services is not defined or "hbase" in services)
    - role: spark/configure
      when: (services is not defined or "spark" in services) and host_in_masters
    - role: hive/configure
      when: (services is not defined or "hive" in services) and host_in_masters
