- hosts: zk_hosts
  become: yes
  roles:
    - role: zookeeper/configure
      when: (services is not defined or "zookeeper" in services) and inventory_hostname in groups['zk_hosts']

- hosts: all
  become: yes
  roles:
    - role: kerberos/configure
      when: services is not defined or "kerberos" in services
    - role: hadoop/configure
      when: services is not defined or "hadoop" in services
    - role: hbase/configure
      when: services is not defined or "hbase" in services

- hosts: masters
  become: yes
  roles:
    - role: spark/configure
      when: services is not defined or "spark" in services
    - role: hive/configure
      when: services is not defined or "hive" in services
