- hosts: all
  become: yes
  roles:
    - role: common/register_running_services
    - role: zookeeper/start
      when: (services is not defined or "zookeeper" in services) and host_in_zk_hosts
    - role: hadoop/format
      when: (services is not defined or "hadoop" in services) and host_in_masters and need_format
    - role: hadoop/start
      when: (services is not defined or "hadoop" in services) and host_in_masters
    - role: hbase/start
      when: (services is not defined or "hbase" in services) and host_in_masters
    - role: spark/prepare
      when: (services is not defined or "spark" in services) and host_in_masters
    - role: spark/start
      when: (services is not defined or "spark" in services) and host_in_masters
    - role: hive/prepare
      when: (services is not defined or "hive" in services) and host_in_masters
    - role: hive/start
      when: (services is not defined or "hive" in services) and host_in_masters
