- hosts: masters
  become: yes
  roles:
    - role: hive/stop
      when: services is not defined or "hive" in services
    - role: spark/stop
      when: services is not defined or "spark" in services
    - role: hbase/stop
      when: services is not defined or "hbase" in services
    - role: hadoop/stop
      when: services is not defined or "hadoop" in services
