- hosts: all
  become: yes
  gather_facts: no
  roles:
    - role: common/configure_host

- hosts: zk_hosts
  become: yes
  gather_facts: no
  roles:
    - role: zookeeper

- hosts: all
  become: yes
  gather_facts: no
  roles:
    - role: hadoop/install

- hosts: masters
  become: yes
  gather_facts: no
  roles:
    - role: hadoop/format
      when: need_format
    - role: hadoop/start

- hosts: all
  become: yes
  gather_facts: no
  roles:
    - role: hbase/install

- hosts: masters
  become: yes
  gather_facts: no
  roles:
    - role: hbase/start

- hosts: masters
  become: yes
  gather_facts: no
  roles:
    - role: spark/install
    - role: spark/start

- hosts: masters
  become: yes
  gather_facts: no
  roles:
    - role: derby/install
    - role: derby/start

- hosts: masters
  become: yes
  gather_facts: no
  roles:
    - role: hive/install

- hosts: masters
  become: yes
  gather_facts: no
  roles:
    - role: airflow/install
    - role: airflow/start
