- import_role:
    role: common/register_running_services

- name: start spark history server
  when: not spark_history_server_is_running
  become_user: spark
  shell: |
    . /etc/bash.bashrc
    nohup /opt/spark/sbin/start-history-server.sh > /opt/spark/logs/spark-history-server.nohup.out
