- import_role:
    name: common/download_service
  vars:
    base: /opt
    url: https://dlcdn.apache.org/hadoop/common/hadoop-3.3.1/hadoop-3.3.1.tar.gz
    archive_file: hadoop-3.3.1.tar.gz
    unarchived_dir: hadoop-3.3.1
    link: hadoop
    templates:
      - etc/hadoop/core-site.xml
      - etc/hadoop/hdfs-site.xml
      - etc/hadoop/mapred-site.xml
      - etc/hadoop/yarn-site.xml
      - etc/hadoop/workers

- name: create data dirs
  file:
    path: "{{ item }}"
    state: directory
    owner: hadoop
    group: hadoop
  loop: "{{ dirs }}"
  vars:
    dirs: "{{ namenode_data_dirs  if is_master_host else datanode_data_dirs }}"
