- import_role:
    name: common/register_running_services

- name: start hbase
  when: not hbase_is_running
  become_user: hadoop
  become_flags: --login
  shell: nohup /opt/hbase/bin/start-hbase.sh > /opt/hbase/logs/hbase.nohup.out
