- import_role:
    role: common/register_running_services

- name: start hbase
  when: not hbase_is_running
  become_user: hbase
  shell: |
    . /etc/bash.bashrc
    nohup /opt/hbase/bin/start-hbase.sh > /opt/hbase/logs/hbase.nohup.out
