- import_role:
    role: common/download_service
  vars:
    url: https://archive.apache.org/dist/hive/hive-3.1.3/apache-hive-3.1.3-bin.tar.gz
    archive_file: apache-hive-3.1.3-bin.tar.gz
    unarchived_dir: apache-hive-3.1.3-bin
    link: hive
    owner: hive

- name: download JDBC driver
  become: yes
  get_url:
    url: https://jdbc.postgresql.org/download/postgresql-42.3.6.jar
    dest: /usr/share/java/postgresql-jdbc-42.3.6.jar
    mode: "644"

- name: link
  file:
    state: link
    src: /usr/share/java/postgresql-jdbc-42.3.6.jar
    dest: /opt/hive/jdbc/postgresql-jdbc.jar

- name: remove duplicate log4j jar
  become_user: hive
  shell: rm -rf /opt/hive/lib/log4j-slf4j-impl-*
