- name: check that hadoop is not running
  fail:
  when: hdfs_is_running or yarn_is_running

- import_role: role=common/kinit
  become_user: "{{ hdfs_user }}"

- name: format namenode
  become_user: "{{ hdfs_user }}"
  shell: yes | {{ opt_dir }}/hadoop/bin/hdfs namenode -format
