- fail:
  when: hdfs_is_running or yarn_is_running

- import_role:
    role: common/kinit
  become_user: hdfs

- name: format namenode
  become_user: hdfs
  shell: |
    . /etc/bash.bashrc
    yes | /opt/hadoop/bin/hdfs namenode -format
