- import_role:
    role: common/register_running_services
  failed_when: hdfs_is_running or yarn_is_running

- name: format namenode
  become_user: hdfs
  shell: |
    . /etc/bash.bashrc
    yes | /opt/hadoop/bin/hdfs namenode -format
