- name: fill configuration files
  template:
    src: "{{ item }}.j2"
    dest: "{{ opt_dir }}/spark/{{ item }}"
    owner: "{{ spark_user }}"
    group: "{{ hadoop_user }}"
  loop:
    - conf/spark-defaults.conf
    - conf/spark-env.sh
