- name: stop mapred
  become_user: mapred
  when: mapred_is_running
  shell: |
    . /etc/bash.bashrc
    /opt/hadoop/bin/mapred --daemon stop historyserver

- name: stop yarn
  become_user: yarn
  when: yarn_is_running
  shell: |
    . /etc/bash.bashrc
    /opt/hadoop/sbin/stop-yarn.sh

- name: stop hdfs
  become: yes
  when: hdfs_is_running
  shell: |
    . /etc/bash.bashrc
    /opt/hadoop/sbin/stop-dfs.sh
