- import_role: role=common/kinit
  become_user: "{{ hdfs_user }}"

- import_role: role=common/kinit
  become_user: "{{ yarn_user }}"

- import_role: role=common/kinit
  become_user: "{{ mapred_user }}"

- name: stop mapred
  become_user: "{{ mapred_user }}"
  when: mapred_is_running
  shell: "{{ opt_dir }}/hadoop/bin/mapred --daemon stop historyserver"

- name: stop yarn
  become_user: "{{ yarn_user }}"
  when: yarn_is_running
  shell: "{{ opt_dir }}/hadoop/sbin/stop-yarn.sh"

- name: stop hdfs
  become: yes
  when: hdfs_is_running
  shell: "{{ opt_dir }}/hadoop/sbin/stop-dfs.sh"
