- import_role:
    name: common/register_running_services

- name: stop mapred
  become_user: hadoop
  become_flags: --login
  when: mapred_is_running
  shell: /opt/hadoop/bin/mapred --daemon stop historyserver

- name: stop yarn
  become_user: hadoop
  become_flags: --login
  when: yarn_is_running
  shell: /opt/hadoop/sbin/stop-yarn.sh

- name: stop hdfs
  become_user: hadoop
  become_flags: --login
  when: hdfs_is_running
  shell: /opt/hadoop/sbin/stop-dfs.sh
