- name: create dirs
  file:
    path: "{{ item }}"
    state: directory
  loop:
    - "{{ opt_dir }}/zookeeper/conf"
    - "{{ zookeeper_data_dir }}"
    - /etc/systemd/system

- name: configure zk
  template:
    src: "opt/{{ item }}.j2"
    dest: "{{ opt_dir }}/{{ item }}"
  loop:
    - zookeeper/conf/zoo.cfg
    - zookeeper/conf/zookeeper-env.sh

- name: configure zk
  template:
    src: "etc/systemd/system/zk.service.j2"
    dest: "/etc/systemd/system/zk-{{ cluster_mode }}.service"

- name: myid
  copy:
    content: "{{ myid }}\n"
    dest: "{{ zookeeper_data_dir }}/myid"
  vars:
    myid: "{{ groups['zk_hosts'].index(inventory_hostname) + 1 }}"

- name: "chown -R {{ zookeeper_user }}:{{ hadoop_user }}"
  file:
    path: "{{ item }}"
    owner: "{{ zookeeper_user }}"
    group: "{{ hadoop_user }}"
    recurse: yes
    state: directory
  loop:
    - "{{ zookeeper_data_dir }}"
