- import_role:
    role: common/register_running_services

- name: stop spark
  become_user: spark
  when: spark_history_server_is_running
  shell: |
    . /etc/bash.bashrc
    /opt/spark/sbin/stop-history-server.sh
