- name: fill configuration files
  template:
    src: "{{ item }}.j2"
    dest: "{{ opt_dir }}/hadoop/{{ item }}"
    owner: "{{ hadoop_user }}"
    group: "{{ hadoop_user }}"
  loop:
    - etc/hadoop/core-site.xml
    - etc/hadoop/hdfs-site.xml
    - etc/hadoop/yarn-site.xml
    - etc/hadoop/mapred-site.xml
    - etc/hadoop/hadoop-policy.xml
    - etc/hadoop/hadoop-env.sh
    - etc/hadoop/workers

- name: create datanode and namenode data dirs
  file:
    path: "{{ item }}"
    state: directory
    owner: "{{ hdfs_user }}"
    group: "{{ hadoop_user }}"
  loop: "{{ datanode_data_dirs + namenode_data_dirs }}"
