- import_role:
    name: common/download_service
  vars:
    base: /opt
    url: https://dlcdn.apache.org/spark/spark-3.2.1/spark-3.2.1-bin-hadoop3.2.tgz
    archive_file: spark-3.2.1-bin-hadoop3.2.tgz
    unarchived_dir: spark-3.2.1-bin-hadoop3.2
    link: spark
    templates:
      - conf/spark-defaults.conf

- name: create spark logs directory in hdfs
  become_user: hadoop
  become_flags: --login
  shell: /opt/hadoop/bin/hdfs dfs -mkdir -p /spark/logs
