- name: execute shell commands
  become_user: hadoop
  become_flags: --login
  shell: "{{ item }}"
  loop:
    - "/opt/hadoop/bin/hdfs dfs -mkdir -p /user/hive/warehouse"
    - "/opt/hadoop/bin/hdfs dfs -mkdir -p /tmp"
    - "/opt/hadoop/bin/hdfs dfs -chmod g+w /user/hive/warehouse"
    - "/opt/hadoop/bin/hdfs dfs -chmod g+w /tmp"
