- name: fill configuration files
  template:
    src: "{{ item }}.j2"
    dest: "{{ opt_dir }}/hbase/{{ item }}"
    owner: "{{ hbase_user }}"
    group: "{{ hadoop_user }}"
  loop:
    - "conf/hbase-env.sh"
    - "conf/hbase-site.xml"
    - "conf/regionservers"
