- name: install packages
  apt:
    update_cache: yes
    pkg: "{{ packages }}"
    state: present
  vars:
    packages:
      - vim
      - net-tools
      - netcat
      - members
      - openjdk-8-jdk
      - lsof
      - net-tools
      - python3
      - python3-pip
      - acl
      - krb5-user
      - libpam-ccreds
      - libpam-krb5
      - jsvc
      - postgresql

- name: pip install
  pip:
    name:
      - pexpect

- name: set JAVA_HOME
  become: yes
  lineinfile:
    path: /etc/environment
    line: JAVA_HOME=/usr/lib/jvm/java-8-openjdk-amd64
    state: present
