- set_fact:
    _base: "{{ base | default('/opt') }}"

- name: "[{{ link }}] debug"
  debug:
    msg:
      {
        base: "{{ _base }}",
        link: "{{ link }}",
        url: "{{ url }}",
        owner: "{{ owner }}",
        unarchived_dir: "{{ unarchived_dir }}",
      }

- name: "[{{ link }}] download service"
  get_url:
    url: "{{ url }}"
    dest: "{{ _base }}/{{ archive_file }}"
    timeout: 60
  environment:
    http_proxy: "{{ http_proxy }}"
    https_proxy: "{{ http_proxy }}"

- name: "[{{ link }}] unarchive"
  unarchive:
    src: "{{ _base }}/{{ archive_file }}"
    dest: "{{ _base }}"
    remote_src: yes
    owner: "{{ owner }}"
    group: hadoop
    creates: "{{ _base }}/{{ unarchived_dir }}"

- name: "[{{ link }}] change owner"
  become: yes
  shell: "chown -R {{ owner }}:hadoop {{ _base }}/{{ unarchived_dir }} "

- name: "[{{ link }}] link"
  file:
    src: "{{ _base }}/{{ unarchived_dir }}"
    path: "{{ _base }}/{{ link }}"
    state: link
    owner: "{{ owner }}"
    group: hadoop

- name: "[{{ link }}] create logs directory"
  file:
    path: "{{ _base }}/{{ link }}/logs"
    state: directory
    owner: "{{ owner }}"
    group: hadoop
    mode: "775"
