- name: "[{{ link }}] debug"
  debug:
    msg:
      {
        link: "{{ link }}",
        url: "{{ url }}",
        owner: "{{ owner }}",
        unarchived_dir: "{{ unarchived_dir }}",
      }

- name: "[{{ link }}] download service"
  get_url:
    url: "{{ url }}"
    dest: "{{ opt_dir }}/{{ archive_file }}"
    timeout: 60
  environment:
    http_proxy: "{{ http_proxy }}"
    https_proxy: "{{ http_proxy }}"

- name: "[{{ link }}] unarchive"
  unarchive:
    src: "{{ opt_dir }}/{{ archive_file }}"
    dest: "{{ opt_dir }}"
    remote_src: yes
    owner: "{{ owner }}"
    group: "{{ hadoop_user }}"
    creates: "{{ opt_dir }}/{{ unarchived_dir }}"

- name: "[{{ link }}] change owner"
  become: yes
  shell: |
    chown -R {{ owner }}:{{ hadoop_user }} {{ opt_dir }}/{{ unarchived_dir }}
    chmod ug+rw -R {{ opt_dir }}/{{ unarchived_dir }}

- name: "[{{ link }}] link"
  file:
    src: "{{ opt_dir }}/{{ unarchived_dir }}"
    path: "{{ opt_dir }}/{{ link }}"
    state: link
    owner: "{{ owner }}"
    group: "{{ hadoop_user }}"

- name: "[{{ link }}] create logs directory"
  file:
    path: "{{ opt_dir }}/{{ link }}/logs"
    state: directory
    owner: "{{ owner }}"
    group: "{{ hadoop_user }}"
    mode: "775"
